version: '3'
services:
  web:
    image: nginx
    ports:
    - 8000:80
    depends_on:
    - php
    - db
    volumes:
    - ./docker/conf/nginx/default.conf:/etc/nginx/conf.d/default.conf
    - .:/var/www/html
    - ./uploads:/var/www/html/uploads

  php:
    build: docker
    volumes:
    - ./docker/conf/php/php.ini:/usr/local/etc/php/conf.d/php.ini
    - ./docker/conf/php/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
    - .:/var/www/html
    - ./uploads:/var/www/html/uploads

  composer:
    image: composer
    volumes:
    - .:/app
    command: install

  db:
    image: postgres:10.1
    restart: always
    environment:
    - POSTGRES_DB=${DB_DATABASE}
    - POSTGRES_USER=${DB_USERNAME}
    - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
    - 5432:5432
    volumes:
    - ./docker/conf/postgres/:/docker-entrypoint-initdb.d/